---
info:
  title: Pycares
  description: Python interface for c-ares
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/pycares
  x-cortex-tag: pycares
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: octo-and-labs
openapi: 3.0.1
servers:
- url: "/"
